"""drop raw_hash from notams

Revision ID: 3942ea6f41d9
Revises: fe3b565a42cc
Create Date: 2025-08-28 11:38:19.015478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3942ea6f41d9'
down_revision: Union[str, Sequence[str], None] = 'fe3b565a42cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notams_replacing_notam'), table_name='notams')
    op.drop_column('notams', 'replacing_notam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notams', sa.Column('replacing_notam', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_notams_replacing_notam'), 'notams', ['replacing_notam'], unique=False)
    # ### end Alembic commands ###
