"""describe change

Revision ID: 6ef737a8440c
Revises: 8a6e2c5131c6
Create Date: 2025-08-30 17:55:22.587106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ef737a8440c'
down_revision: Union[str, Sequence[str], None] = '8a6e2c5131c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notams', 'time_classification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notams', sa.Column('time_classification', sa.VARCHAR(length=14), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
