"""add password reset codes table

Revision ID: b0533ae16ec5
Revises: a0299faefcd5
Create Date: 2025-09-13 10:42:18.868292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0533ae16ec5'
down_revision: Union[str, Sequence[str], None] = 'a0299faefcd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_codes',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index('idx_password_reset_expires', 'password_reset_codes', ['expires_at'], unique=False)
    op.create_index(op.f('ix_notams_is_active'), 'notams', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notams_is_active'), table_name='notams')
    op.drop_index('idx_password_reset_expires', table_name='password_reset_codes')
    op.drop_table('password_reset_codes')
    # ### end Alembic commands ###
