"""initial schema

Revision ID: b3a325343fca
Revises: 
Create Date: 2025-08-17 05:41:37.936668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a325343fca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_notam_aircraft_propulsions'), 'notam_aircraft_propulsions', type_='unique')
    op.drop_constraint(op.f('uq_notam_aircraft_sizes'), 'notam_aircraft_sizes', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_notam_aircraft_sizes'), 'notam_aircraft_sizes', ['notam_id', 'size'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_notam_aircraft_propulsions'), 'notam_aircraft_propulsions', ['notam_id', 'propulsion'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
