"""describe change

Revision ID: bafb1fc857f1
Revises: acc9c970c618
Create Date: 2025-08-30 18:04:50.993451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafb1fc857f1'
down_revision: Union[str, Sequence[str], None] = 'acc9c970c618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notam_obstacles', 'offset_distance_m')
    op.drop_column('notam_obstacles', 'reference_type')
    op.drop_column('notam_obstacles', 'corridor_orientation')
    op.drop_column('notam_obstacles', 'offset_direction')
    op.drop_column('notam_obstacles', 'runway_id')
    op.drop_column('notam_obstacles', 'lateral_half_width_m')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notam_obstacles', sa.Column('lateral_half_width_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('notam_obstacles', sa.Column('runway_id', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('notam_obstacles', sa.Column('offset_direction', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('notam_obstacles', sa.Column('corridor_orientation', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('notam_obstacles', sa.Column('reference_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('notam_obstacles', sa.Column('offset_distance_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
