"""restore replacing_notam; drop raw_hash

Revision ID: edcec6ef9eb2
Revises: 3942ea6f41d9
Create Date: 2025-08-28 11:40:11.238855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edcec6ef9eb2'
down_revision: Union[str, Sequence[str], None] = '3942ea6f41d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notams', sa.Column('replacing_notam', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_notams_replacing_notam'), 'notams', ['replacing_notam'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notams_replacing_notam'), table_name='notams')
    op.drop_column('notams', 'replacing_notam')
    # ### end Alembic commands ###
