"""describe change

Revision ID: fab78ed1628c
Revises: edcec6ef9eb2
Create Date: 2025-08-28 13:40:33.355366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fab78ed1628c'
down_revision: Union[str, Sequence[str], None] = 'edcec6ef9eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notams', 'score_explanation_vfr')
    op.drop_column('notams', 'score_features_ifr')
    op.drop_column('notams', 'score_features_vfr')
    op.drop_column('notams', 'score_explanation_ifr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notams', sa.Column('score_explanation_ifr', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.add_column('notams', sa.Column('score_features_vfr', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notams', sa.Column('score_features_ifr', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('notams', sa.Column('score_explanation_vfr', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
