# notam/core/enums.py
"""
Unified enums for the NOTAM analysis system.
Consolidates all enum definitions from db.py and models.py.
"""
import enum


class NotamCategoryEnum(str, enum.Enum):
    """NOTAM scope classification"""
    FIR = "FIR"
    AIRPORT = "AIRPORT"


class SeverityLevelEnum(str, enum.Enum):
    """Enhanced severity classification"""
    CRITICAL = "CRITICAL"
    OPERATIONAL = "OPERATIONAL"
    ADVISORY = "ADVISORY"


class TimeClassificationEnum(str, enum.Enum):
    """Time-based classification of NOTAMs"""
    PERMANENT = "PERMANENT"
    LONG_TERM = "LONG_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"
    SHORT_TERM = "SHORT_TERM"
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    EVENT_SPECIFIC = "EVENT_SPECIFIC"


class TimeOfDayApplicabilityEnum(str, enum.Enum):
    """Time of day when NOTAM applies"""
    DAY = "DAY ONLY"
    NIGHT = "NIGHT ONLY"
    ALL = "ALL TIMES"


class FlightRuleApplicabilityEnum(str, enum.Enum):
    """Flight rules the NOTAM applies to"""
    VFR_ONLY = "VFR ONLY"
    IFR_ONLY = "IFR ONLY"
    ALL = "ALL RULES"


class AircraftSizeEnum(str, enum.Enum):
    """Aircraft size categories based on ICAO wake turbulence"""
    ALL = "ALL"
    LIGHT = "LIGHT"
    MEDIUM = "MEDIUM"
    HEAVY = "HEAVY"
    SUPER = "SUPER"


class AircraftPropulsionEnum(str, enum.Enum):
    """Aircraft propulsion types"""
    ALL = "ALL"
    JET = "JET"
    TURBOPROP = "TURBOPROP"
    PISTON = "PISTON"
    HELICOPTER = "HELICOPTER"


class FlightPhaseEnum(str, enum.Enum):
    """Flight phases affected by NOTAM"""
    PREFLIGHT = "PREFLIGHT"
    TAXI = "TAXI"
    TAKEOFF = "TAKEOFF"
    DEPARTURE = "DEPARTURE"
    CRUISE = "CRUISE"
    APPROACH = "APPROACH"
    ARRIVAL = "ARRIVAL"
    GROUND_OPS = "GROUND_OPS"
    ALL_PHASES = "ALL_PHASES"


class PrimaryCategoryEnum(str, enum.Enum):
    """Primary operational categories for NOTAMs"""
    RUNWAY_OPERATIONS = "RUNWAY_OPERATIONS"
    AERODROME_OPERATIONS = "AERODROME_OPERATIONS"
    NAVAIDS_SID_STAR_APPROACH_PROCEDURES = "NAVAIDS_SID_STAR_APPROACH_PROCEDURES"
    FLOW_CONTROL = "FLOW_CONTROL"
    COMMUNICATION_SERVICES = "COMMUNICATION_SERVICES"
    OBSTACLES = "OBSTACLES"
    RESTRICTED_AREA = "RESTRICTED_AREA"
    ROUTING = "ROUTING"
    MILITARY_ACTIVITY = "MILITARY_ACTIVITY"


class OperationalTagEnum(str, enum.Enum):
    """Detailed operational tags for specific NOTAM impacts"""
    # Airport and Runway Operations
    AIRPORT_CLOSURE = "AIRPORT_CLOSURE"
    RUNWAY_CLOSURE = "RUNWAY_CLOSURE"
    RUNWAY_LENGTH_REDUCTION = "RUNWAY_LENGTH_REDUCTION"
    DISPLACED_RUNWAY_THRESHOLD = "DISPLACED_RUNWAY_THRESHOLD"
    RUNWAY_SURFACE_CONTAMINATION = "RUNWAY_SURFACE_CONTAMINATION"
    BRAKING_ACTION_REPORT = "BRAKING_ACTION_REPORT"
    RUNWAY_SURFACE_CONDITION_REPORT = "RUNWAY_SURFACE_CONDITION_REPORT"

    # Lighting Systems
    TAXIWAY_LIGHT_UNSERVICEABLE = "TAXIWAY_LIGHT_UNSERVICEABLE"
    RUNWAY_LIGHTS_UNSERVICEABLE = "RUNWAY_LIGHTS_UNSERVICEABLE"
    APPROACH_LIGHTS_UNSERVICEABLE = "APPROACH_LIGHTS_UNSERVICEABLE"
    PAPI_VASI_UNSERVICEABLE = "PAPI_VASI_UNSERVICEABLE"
    AERODROME_BEACON_UNSERVICEABLE = "AERODROME_BEACON_UNSERVICEABLE"

    # Ground Movement
    TAXIWAY_CLOSURE = "TAXIWAY_CLOSURE"
    TAXIWAY_RESTRICTION = "TAXIWAY_RESTRICTION"
    WINGSPAN_RESTRICTION = "WINGSPAN_RESTRICTION"
    RUNUP_APRON_CLOSURE = "RUNUP_APRON_CLOSURE"
    RAMP_CLOSURE = "RAMP_CLOSURE"
    GATE_RESTRICTION = "GATE_RESTRICTION"
    RUNWAY_HOLD_POSITION_CHANGE = "RUNWAY_HOLD_POSITION_CHANGE"

    # Airspace and Activities
    AIRSPACE_RESTRICTIONS = "AIRSPACE_RESTRICTIONS"
    PROHIBITED_AREA_ACTIVE = "PROHIBITED_AREA_ACTIVE"
    RESTRICTED_DANGER_AREA_ACTIVE = "RESTRICTED_DANGER_AREA_ACTIVE"
    MILITARY_ACTIVITY_ACTIVE = "MILITARY_ACTIVITY_ACTIVE"
    DRONE_ACTIVITY = "DRONE_ACTIVITY"
    LASER_ACTIVITY = "LASER_ACTIVITY"
    LIGHT_SHOW = "LIGHT_SHOW"

    # Navigation and Communication
    NAVIGATION_AID_TESTING = "NAVIGATION_AID_TESTING"
    NAVAID_UNSERVICEABLE = "NAVAID_UNSERVICEABLE"
    DEGRADED_NAVAID = "DEGRADED_NAVAID"
    ILS_UNSERVICEABLE = "ILS_UNSERVICEABLE"
    DEGRADED_ILS = "DEGRADED_ILS"
    DME_UNSERVICEABLE = "DME_UNSERVICEABLE"
    DEGRADED_DME = "DEGRADED_DME"
    RNP_RNAV_GNSS_DISRUPTION = "RNP_RNAV_GNSS_DISRUPTION"
    MARKER_LOCATOR_UNSERVICEABLE = "MARKER_LOCATOR_UNSERVICEABLE"
    ADSB_COVERAGE_LIMITATION = "ADSB_COVERAGE_LIMITATION"
    COMMS_FREQUENCY_CHANGE = "COMMS_FREQUENCY_CHANGE"
    NAVAID_FREQUENCY_CHANGE = "NAVAID_FREQUENCY_CHANGE"
    CPDLC_UNAVAILABLE = "CPDLC_UNAVAILABLE"
    ATS_UNAVAILABLE = "ATS_UNAVAILABLE"

    # Procedures
    SID_PROCEDURES_CHANGE = "SID_PROCEDURES_CHANGE"
    STAR_PROCEDURES_CHANGE = "STAR_PROCEDURES_CHANGE"
    APPROACH_PROCEDURE_CHANGE = "APPROACH_PROCEDURE_CHANGE"
    DEPARTURE_APPROACH_MINIMA_CHANGE = "DEPARTURE_APPROACH_MINIMA_CHANGE"
    MISSED_APPROACH_PROCEDURE_CHANGE = "MISSED_APPROACH_PROCEDURE_CHANGE"
    CLIMB_GRADIENT_CHANGE = "CLIMB_GRADIENT_CHANGE"

    # Weather and Visibility
    RVR_EQUIPMENT_UNSERVICEABLE = "RVR_EQUIPMENT_UNSERVICEABLE"
    INSTRUMENT_APPROACH_UNAVAILABLE = "INSTRUMENT_APPROACH_UNAVAILABLE"
    CAT_II_III_UNAVAILABLE = "CAT_II_III_UNAVAILABLE"
    LOW_VISIBILITY_OPERATIONS_SUSPENDED = "LOW_VISIBILITY_OPERATIONS_SUSPENDED"
    WEATHER_AID_UNSERVICEABLE = "WEATHER_AID_UNSERVICEABLE"

    # Obstacles and Hazards
    UNLIT_OBSTACLE = "UNLIT_OBSTACLE"
    OBSTACLE_HAZARD = "OBSTACLE_HAZARD"
    WILDLIFE_ACTIVITY = "WILDLIFE_ACTIVITY"
    RUNWAY_TAXIWAY_FOD_HAZARD = "RUNWAY_TAXIWAY_FOD_HAZARD"

    # Services and Support
    FUEL_UNAVAILABLE = "FUEL_UNAVAILABLE"
    DEICING_UNAVAILABLE = "DEICING_UNAVAILABLE"
    ARFF_INDEX_REDUCED = "ARFF_INDEX_REDUCED"
    FLIGHT_PLANNING_SERVICE_UNAVAILABLE = "FLIGHT_PLANNING_SERVICE_UNAVAILABLE"
    AOG_SUPPORT_LIMITED = "AOG_SUPPORT_LIMITED"

    # Administrative
    PUBLICATION_AMENDMENT = "PUBLICATION_AMENDMENT"
    NOISE_ABATEMENT = "NOISE_ABATEMENT"
    DESIGNATOR_CHANGE = "DESIGNATOR_CHANGE"

    # Flow Control
    ATFM_RESTRICTIONS = "ATFM_RESTRICTIONS"

    # Special Operations
    SAR_RELATED = "SAR_RELATED"
    CIRCUIT_TRAINING_RESTRICTION = "CIRCUIT_TRAINING_RESTRICTION"

    # Routing
    ENROUTE_ROUTE_CHANGE = "ENROUTE_ROUTE_CHANGE"


# Backward compatibility aliases (remove these gradually)
NotamCategory = NotamCategoryEnum
SeverityLevel = SeverityLevelEnum
FlightPhase = FlightPhaseEnum
TimeOfDayApplicability = TimeOfDayApplicabilityEnum
FlightRuleApplicability = FlightRuleApplicabilityEnum
AircraftSize = AircraftSizeEnum
AircraftPropulsion = AircraftPropulsionEnum
PrimaryCategory = PrimaryCategoryEnum
OperationalTag = OperationalTagEnum